baseurl = "https://lernisto.com/"
languageCode = "en-us"
title = "You Can Learn Anything"
copyright = "<a rel='license' nofollow href='http://creativecommons.org/licenses/by-sa/4.0/'><img alt='Creative Commons License' style='border-width:0' src='https://i.creativecommons.org/l/by-sa/4.0/80x15.png' /></a><br /><span xmlns:dct='http://purl.org/dc/terms/' property='dct:title'>Lernisto.com</span> by <a xmlns:cc='http://creativecommons.org/ns#' href='https://lernisto.com/terrel/' property='cc:attributionName' rel='cc:attributionURL'>Terrel Shumway</a> is licensed under a <a rel='license' nofollow href='http://creativecommons.org/licenses/by-sa/4.0/'>Creative Commons Attribution-ShareAlike 4.0 International License</a>."

[params]
  logo      = "/images/logo.svg"
  twitter   = "https://twitter.com/lernisto"
  github    = "https://github.com/lernisto/"
  email     = "uyc4e6sri7mwy@lernisto.com"
